# Generated by Django 5.2.8 on 2025-11-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, unique=True)),
                ('hoc_ham_hoc_vi', models.CharField(blank=True, help_text='Ví dụ: TS. hoặc PGS.TS.', max_length=100)),
            ],
            options={
                'verbose_name': 'Cán bộ hướng dẫn',
                'verbose_name_plural': 'Cán bộ hướng dẫn',
            },
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('que_quan', models.CharField(blank=True, max_length=255)),
                ('cbhd', models.ManyToManyField(blank=True, related_name='hoc_vien_huong_dan', to='core.cbhd')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': 'Danh sách Học viên',
            },
        ),
        migrations.CreateModel(
            name='DeCuong',
            fields=[
                ('hoc_vien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.hocvien')),
                ('ten_de_tai', models.TextField()),
                ('ly_do_chon_de_tai', models.TextField(blank=True, null=True)),
                ('khung_ly_thuyet', models.TextField(blank=True, null=True, verbose_name='Chương 1: Khung lý thuyết')),
                ('thiet_ke_va_to_chuc', models.TextField(blank=True, null=True, verbose_name='Chương 2: Thiết kế/Tổ chức')),
                ('thuc_nghiem', models.TextField(blank=True, null=True, verbose_name='Chương 3: Thực nghiệm')),
                ('trang_thai', models.CharField(choices=[('ban_nhap', 'Bản nháp'), ('da_nop', 'Đã nộp'), ('da_duyet', 'Đã duyệt'), ('can_chinh_sua', 'Cần chỉnh sửa')], default='ban_nhap', max_length=20)),
            ],
            options={
                'verbose_name': 'Đề cương',
                'verbose_name_plural': 'Quản lý Đề cương',
            },
        ),
    ]
